version: 2
jobs: 
  build: 
    working_directory: ~/zing-lite-rails-api
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          PGHOST: localhost
          PGUSER: zing-lite-rails-api
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: zing-lite-rails-api
          POSTGRES_DB: zing-lite-rails-api_test
          POSTGRES_PASSWORD: "password"
    steps: 
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: zing-lite-rails-api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: zing-lite-rails-api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake